/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame.view;

import booking.Booking;
import testingSite.TestingSite;
import testingSite.TestingSiteSingleton;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Suchit Krishna
 */
public class RestoreView extends javax.swing.JFrame {
    Booking booking;
    /**
     * Creates new form RestoreFrame
     */
    public RestoreView(Booking booking) {
        this.booking = booking;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restoreLbl = new javax.swing.JLabel();
        venueBox = new JComboBox<TestingSite>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        timeBox = new javax.swing.JComboBox<>();
        confirmBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        restoreLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        restoreLbl.setText("Restore Booking");

        venueBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Testing Venue:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Venue Time:");

        timeBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        confirmBtn.setText("Confirm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(restoreLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(venueBox, 0, 282, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(timeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(confirmBtn)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restoreLbl)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(venueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(timeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Booking getBooking(){
        return booking;
    }

    public JComboBox<String> getTimeBox() {
        return timeBox;
    }

    public JComboBox<TestingSite> getVenueBox() {
        return venueBox;
    }

    public void addConfirmActionListener(ActionListener actionListener){
        confirmBtn.addActionListener(actionListener);
    }

    public void showBookings() throws IOException, InterruptedException {
        if (booking.getAdditionalInfo().get("bookingMemento")== null){
            JOptionPane.showMessageDialog(null,  "No bookings to restore please return!");
        }
        else {
            TestingSiteSingleton testingSiteSingleton = TestingSiteSingleton.getInstance();
            testingSiteSingleton.loadTestingSites();
            ArrayList<TestingSite> testingSites = testingSiteSingleton.getTestingSites();
            venueBox.addItem(null);
            timeBox.addItem(null);

            String bookingOneId = booking.getAdditionalInfo().get("bookingMemento").get("bookingOne").get("testingSiteId").asText();
            String bookingTwoId = "None";
            String bookingThreeId = "None";

            if (booking.getAdditionalInfo().get("bookingMemento").get("bookingTwo")!= null){
                bookingTwoId = booking.getAdditionalInfo().get("bookingMemento").get("bookingTwo").get("testingSiteId").asText();
            }
            if (booking.getAdditionalInfo().get("bookingMemento").get("bookingThree")!= null){
                bookingThreeId =  booking.getAdditionalInfo().get("bookingMemento").get("bookingThree").get("testingSiteId").asText();
            }
            for (TestingSite testingSite:testingSites) {
                if (testingSite.getId().equals(bookingThreeId)) {
                    venueBox.addItem(testingSite);
                    timeBox.addItem(booking.getAdditionalInfo().get("bookingMemento").get("bookingThree").get("startTime").asText());
                }
                if (testingSite.getId().equals(bookingTwoId)) {
                    timeBox.addItem(booking.getAdditionalInfo().get("bookingMemento").get("bookingTwo").get("startTime").asText());
                    venueBox.addItem(testingSite);
                }
                if (testingSite.getId().equals(bookingOneId)) {
                    timeBox.addItem(booking.getAdditionalInfo().get("bookingMemento").get("bookingOne").get("startTime").asText());
                    venueBox.addItem(testingSite);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestoreView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestoreView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestoreView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestoreView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new RestoreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel restoreLbl;
    private javax.swing.JComboBox<String> timeBox;
    private JComboBox<TestingSite> venueBox;
    // End of variables declaration//GEN-END:variables
}
